module.exports = function() {
	return {
		IQ_MAX_QUESTIONS_FOR_NON_MEMBERS: 5,
		GK_MAX_QUESTIONS_FOR_NON_MEMBERS: 10,
		MATCH_MAX_TRIALS_FOR_NON_MEMBERS: 10,
		FREE_IQ_WEIGHT: 50,
		EASY_IQ_WEIGHT: 110,
		MEDIUM_IQ_WEIGHT: 80,
		HARD_IQ_WEIGHT: 60,

		IQ_TIME_LIMIT_EASY: 60,
		IQ_TIME_LIMIT_MEDIUM: 100,
		IQ_TIME_LIMIT_HARD: 140,

		GK_TIME_LIMIT: 10,

		PROFILE_IQ_QUESTION: 1,
		PROFILE_GK_QUESTION: 2
	};
};